<?php

namespace OrganisationBundle\Repository;

/**
 * JoueurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JoueurRepository extends \Doctrine\ORM\EntityRepository
{
    public function trouverTousJoueur(){
        $query = $this->_em->createQuery("SELECT j FROM OrganisationBundle:Joueur j");
        return $query->getResult();
    }
}
