<?php

namespace OrganisationBundle\Repository;

/**
 * MatchsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllMatchs(){
        $query = $this->_em->createQuery("SELECT m FROM OrganisationBundle:Matchs m");
        return $query->getResult();
    }
}
