# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    organisation.match_mailer:
        class: OrganisationBundle\EventListener\MatchSubscriber
        arguments: ['@doctrine.orm.entity_manager', '@swiftmailer.mailer']
